print('hi')
print('mohanjhsdhsduehuhwe')
print('jith')
print('jdnfoweoifjowierfiojerru9403nnm ncjdncjnd')
print('hjdnfoe')
print('hi')
print('asoifhjeoihfoa')
print('hi')
print('jaynathi')
print('hi')
print('hi')
print('akshitha')
print('hi')
